<?php

/**
 * Implements hook_views_api().
 */
function drupal_extra_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'drupal_extra') . '/includes',
  );
}

/**
 * Implementation of hook_views_query_alter
 * @param type $view
 * @param type $query
 */
function drupal_extra_views_query_alter(&$view, &$query) {
  if (is_array($view->filter)) {
    foreach ($view->filter as $k => $v) {
      __drupal_extra_views_query_alter($view, $query, $v);
    }
  }
  if (is_array($view->relationship)) {
    foreach ($view->relationship as $k => $v) {
      // dextra|table:field_all_turns FEATURE
      __drupal_extra_views_query_alter($view, $query, $v);
    }
  }
}
function __drupal_extra_views_query_alter(&$view, &$query, $v) {
  if (isset($v->options['ui_name']) && $v->options['ui_name'] && strpos($v->options['ui_name'], 'dextra') !== FALSE) {
    $options = drupal_extra_to_options($v->options['ui_name']);
    if (isset($options['equal']) || isset($options['contain'])) {
      $field = $v->table_alias . '.' . $v->field;
      foreach ($query->where as $key => $cond) {
        if (!isset($cond['conditions'])) {
          continue ;
        }
        foreach ($cond['conditions'] as $subkey => $subcond) {
          if (!isset($subcond['field'])) {
            continue ;
          }
          if ($subcond['field'] == $field && $subcond['operator'] == 'IS NOT NULL') {
            $query->where[$key]['conditions'][$subkey]['operator'] = 'LIKE';
            $date = drupal_extra_views_get_argument_smart($view, 'date');
            $query->where[$key]['conditions'][$subkey]['value'] = '%' . $date;
          }
        }
      }
    }
    if (isset($options['table'])) {
      $table = $v->table;// Consider to use $v->alias Could buggy here
      if (isset($query->table_queue[$table])) {
        $query->table_queue[$table]['join']->table = $query->table_queue[$table]['table'] = $options['table'];
      }
    }
    if (isset($options['morejoin'])) {
      unset($query->table_queue['field_data_field_agent']);
      $table = $v->alias;// Consider to use $v->alias Could buggy here
      if (isset($query->table_queue[$table])) {
        $query->table_queue[$table]['join']->table = $query->table_queue[$table]['table'] = 'eck_daily_report_agents';
        $query->table_queue[$table]['join']->left_table = 'users';
        $query->table_queue[$table]['join']->left_field = 'uid';
        $query->table_queue[$table]['join']->field = 'field_agent_target_id';
      }
    }
    if (isset($options['join'])) {
      $table = $v->alias;
      $date = drupal_extra_views_get_argument_smart($view, 'date');

      $query->table_queue[$table]['join']->extra = array('' . $table . '.title LIKE \'%'. $date .'\'');
    }
  }
}

function drupal_extra_views_get_argument_smart($view, $key) {
  $date = isset($view->args[0]) ? $view->args[0] : '';
  if (isset($view->exposed_input[$key])) {
    $date = $view->exposed_input[$key];
  }
  else if (isset($_GET[$key])) {
    $date = $_GET[$key];
  }
  return $date;
}

function drupal_extra_to_options($string) {
  list(, $options) = strpos($string, "|") !== FALSE ? explode("|", $string) : array(0, $string);
  $options = explode(",", $options);
  $options = array_map("trim", $options);
  $options = array_reduce($options, function ($result, $item) {
    $item = explode(":", $item);
    $result[$item[0]] = isset($item[2]) ? $item : $item[1];
    return $result;
  }, array());
  return $options;
}

/**
TODO: MOve states_extra to this module
 * Implement of hook_page_alter
 */
function drupal_extra_page_alter() {
  drupal_add_js(drupal_get_path('module', 'drupal_extra') . '/conditional_fields_extra.js');
}

/**
 * Implement of hook_conditional_fields_states_alter
 */
function drupal_extra_conditional_fields_states_alter(&$states) {
  $states['hideselectedoption'] = t('Hide selected option');
  $states['!hideselectedoption'] = t('Hide others but selected option');
}

/**
 * Implement of hook_conditional_fields_conditions_alter
 */
function drupal_extra_conditional_fields_conditions_alter(&$conditions) {
  $conditions['valuechange'] = t('Value is changed');
  // Like states, conditions get a converse automatically.
  $conditions['!valuechange'] = t('Value is not changed');
}

/**
 * Implement of hook_js_alter
 */
function drupal_extra_js_alter(&$javascript) {
  if (array_key_exists('misc/ajax.js', $javascript)) {
    $ajax_extra = drupal_get_path("module", "drupal_extra") . "/ajax.extra.js";
    $javascript[$ajax_extra] = $javascript['misc/ajax.js'];
    $javascript[$ajax_extra]['data'] = $ajax_extra;
    $javascript[$ajax_extra]['weight']++;
  }
}


function computed_field_recalculate_field_simple($entity, $type, $field) {
  static $info;
  $info = isset($info) ? $info : entity_get_info();
  return computed_field_recalculate_field($info[$type]['base table'], $type, $entity, $field);
}

// computed_field_recalculate_field("users", "user", user_load(1), 'field_balance');
function computed_field_recalculate_field($table, $type, $entity, $field_name) {
  static $calculated;
  $info = entity_get_info();
  $idkey = $info[$type]['entity keys']['id'];
  $bundlekey = $info[$type]['entity keys']['bundle'];
  if (!isset($entity->{$bundlekey})) {
    $bundle = $type;
  }
  else {
    $bundle = $entity->{$bundlekey};
  }

  $entities_by_type = array($type => array($bundle));
  $entities_per_run = 1;

  $itemkey = $table . $type . $entity->{$idkey};
  if (isset($calculated[$itemkey])) {
    return ;
  }
  $calculated[$itemkey] = TRUE;

  $context = array();
  $context['sandbox']['offsets_by_type'] = array();
  $context['sandbox']['offsets_by_type'][$type]['offset'] = _help_offset_entity($table, $type, $entity, $field_name, $bundle);
  $context['sandbox']['offsets_by_type'][$type]['types'] = array($bundle);
  $context['sandbox']['max_ids'] = array($type => $entity->{$idkey});
  $context['results']['total_entities_touched'] = 0;
  $context['results']['start'] = REQUEST_TIME;
  $context['results']['end'] = 0;
  $context['results']['total_id_count'] = 1;

  _computed_field_tools_batch_recompute($entities_by_type, $field_name, $entities_per_run, $context);
}

function _help_offset_entity($table, $type, $entity, $field_name, $bundle) {
  if ($type != 'taxonomy_term') {
    return 0;
  }
  $vids = db_select('taxonomy_vocabulary', 'tv')
    ->fields('tv', array('vid'))
    ->condition('machine_name', array($bundle), 'IN')
    ->execute()
    ->fetchCol();

  $query = db_select('taxonomy_term_data', 'n')
    ->condition('n.tid', $entity->tid, '<')
    ->condition('vid', $vids, 'IN')
    ->orderBy('n.tid', 'ASC');
  return $query->countQuery()->execute()->fetchField();
}

function drupal_extra_create_field_all_view($fieldname) {
  return db_query("CREATE VIEW field_data_{$fieldname}_value_all AS
  SELECT *, GROUP_CONCAT(DISTINCT CONCAT('(', {$fieldname}_value, ')') SEPARATOR '+') as {$fieldname}_value_merged FROM {field_data_{$fieldname}}
  GROUP BY entity_id");
}
