<?php

/**
 * Implements hook_page_alter().
 */
function visitors_extra_page_alter(&$page) {
  // Attach Ajax page count visitors_extra if configured.
  if (variable_get('visitors_extra_views_ajax', 0)) {
    $visitors_extra = drupal_get_path('module', 'visitors_extra') . '/visitors_extra.js';
    $page['content']['#attached']['js'][$visitors_extra] = array(
      'scope' => 'footer',
    );
    $url = url(drupal_get_path('module', 'visitors_extra') . '/visitors_extra.php');
    $n = menu_get_object();
    $nuuid = isset($n->uuid) ? $n->uuid : "";
    $settings = array('data' => array(
      'visitors_get_nid_uuid' => $nuuid,
      'visitors_get_url' => visitors_get_url(),
      'visitors_get_referer' => visitors_get_referer(),// This is fixed via JS
      'visitors_get_path' => visitors_get_path(),
      'visitors_get_title' => visitors_get_title(),
      'url' => $url,
    ), 'url' => $url);
    $page['content']['#attached']['js'][] = array(
      'data' => array('visitors_extra' => $settings),
      'type' => 'setting',
    );
  }
}

function visitors_extra_do_insert($fields, $fulldata = array()) {
  $ip_str = $fields['visitors_ip'];
  if (module_exists('visitors_geoip')) {
    $geoip_data = visitors_get_geoip_data($ip_str);

    $fields['visitors_continent_code'] = $geoip_data['continent_code'];
    $fields['visitors_country_code']   = $geoip_data['country_code'];
    $fields['visitors_country_code3']  = $geoip_data['country_code3'];
    $fields['visitors_country_name']   = $geoip_data['country_name'];
    $fields['visitors_region']         = $geoip_data['region'];
    $fields['visitors_city']           = $geoip_data['city'];
    $fields['visitors_postal_code']    = $geoip_data['postal_code'];
    $fields['visitors_latitude']       = $geoip_data['latitude'];
    $fields['visitors_longitude']      = $geoip_data['longitude'];
    $fields['visitors_dma_code']       = $geoip_data['dma_code'];
    $fields['visitors_area_code']      = $geoip_data['area_code'];
  }

  db_insert('visitors')
    ->fields($fields)
    ->execute();

  module_invoke_all("visitors_insert", $fields, $fulldata);
}
